version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    networks:
    - traefik-net
    volumes:
    - data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    deploy:
      labels:
      - :traefik.enable=true
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.docker.network=traefik-net"



volumes:
  data:
networks:
  traefik-net:
    external: true
