version: '3'

services:
  traefik-ingress:
    image: traefik:v3.0
    command:
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--providers.docker"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker.swarmmode=true"
    - "--providers.docker.network=traefik-net"
    - "--api"
    - "--api.insecure=true"
    - "--api.dashboard=true"
    ports:
    - "80:80"
    - "443:443" #for traefik dashboard
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    # Make sure the volume folder is created
    - '/mnt/data/traefik/acme.json:/le/acme.json'
    networks:
    - traefik-net
    deploy:
      labels:
      # Dashboard
      - 'traefik.enable=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      placement:
        constraints:
        - node.role==manager

  my-app:
    image: containous/whoami:v1.3.0
    networks:
    - traefik-net
    command:
    - --port=8082 # Our service listens on 8082
    deploy:
      labels:
      - 'traefik.enable=true'
      # Change the host url here
      - 'traefik.http.services.my-app.loadbalancer.server.port=8082'

  portainer:
    image: portainer/portainer-ce:latest
    ports:
    - 9443:9443
    volumes:
    - data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  traefik-net:
    external: true
