version: '3.3'

services:
  traefik-ingress:
    image: traefik:v3.0
    command:
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--providers.docker"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker.swarmmode=true"
    - "--providers.docker.swarmModeRefreshSeconds=30"
    - "--ping=true"
    - "--accesslog=true"
    - "--providers.docker.network=traefik-net"
    - "--api"
    - "--api.insecure=true"
    - "--api.dashboard=true"
    ports:
    - "80:80"
    - "8443:8080" #for traefik dashboard
    networks:
    - traefik-net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    # Make sure the volume folder is created
    - '/mnt/data/traefik/acme.json:/le/acme.json'
    deploy:
      labels:
      # Dashboard
      - 'traefik.enable=true'
      placement:
        constraints:
        - node.role==manager
networks:
  traefik-net:
    external: true
