version: '3.3'

services:
  my-app:
    image: containous/whoami:v1.3.0
    networks:
    - traefik-net
    deploy:
      labels:
      - 'traefik.enable=true'
      # Change the host url here
      - 'traefik.http.services.my-app.loadbalancer.server.port=8082'

  portainer:
    image: portainer/portainer-ce:latest
    ports:
    - 9443:9443
    networks:
    - traefik-net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/volume2/portainer:/data
    restart: unless-stopped
    deploy:
      placement:
        constraints:
        - node.role==manager
      labels:
      - 'traefik.enable=true'
      # Change the host url here
      - 'traefik.http.services.my-app.loadbalancer.server.port=9443'
  traefik-ingress:
    image: traefik:v3.0
    command:
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--providers.docker"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker.swarmmode=true"
    - "--providers.docker.network=traefik-net"
    - "--api"
    - "--api.insecure=true"
    - "--api.dashboard=true"
    ports:
    - "80:80"
    - "8443:8080" #for traefik dashboard
    - "9000:9433"
    - "8000:8082"
    networks:
    - traefik-net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    # Make sure the volume folder is created
    - '/mnt/data/traefik/acme.json:/le/acme.json'
    deploy:
      labels:
      # Dashboard
      - 'traefik.enable=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      placement:
        constraints:
        - node.role==manager


networks:
  traefik-net:
    external: true
